### ISSUE TITLE
Publish webrtc_vad.js as npm module?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/webrtcvad_js#1]
Ref: https://github.com/mozilla/speaktome/issues/114

Not sure if we use this code in a lot of places, but it might be nice to add a package.json to this repo with a name+version+repo and then publish the webrtc_vad.js+LICENSE to npm for easier consumption (and less copy pastey).

**UPDATE:** Published as https://www.npmjs.com/package/webrtcvad_js

**Comment by ohtangza** [comment]
I saw your pull requests. Thanks for your effort!

**Comment by andrenatal** [comment]
Yes, I just merged it and published to npm. Just run: `npm install webrtcvad_js`
